/** Generated from plumbit-erp-be/app/auth/catalog.py — do not edit manually. */
/** Regenerate: npm run generate:permissions */

export const catalogPermissions = [
  "accounting.account.create",
  "accounting.account.delete",
  "accounting.account.read",
  "accounting.account.update",
  "accounting.bank_account.create",
  "accounting.bank_account.delete",
  "accounting.bank_account.read",
  "accounting.bank_account.update",
  "accounting.bank_reconciliation.create",
  "accounting.bank_reconciliation.delete",
  "accounting.bank_reconciliation.export",
  "accounting.bank_reconciliation.import",
  "accounting.bank_reconciliation.read",
  "accounting.bank_reconciliation.reconcile",
  "accounting.bank_reconciliation.update",
  "accounting.budget.activate",
  "accounting.budget.close",
  "accounting.budget.create",
  "accounting.budget.delete",
  "accounting.budget.read",
  "accounting.budget.update",
  "accounting.charge_type.create",
  "accounting.charge_type.delete",
  "accounting.charge_type.read",
  "accounting.charge_type.update",
  "accounting.cheque.bounce",
  "accounting.cheque.cancel",
  "accounting.cheque.clear",
  "accounting.cheque.create",
  "accounting.cheque.delete",
  "accounting.cheque.deposit",
  "accounting.cheque.issue",
  "accounting.cheque.read",
  "accounting.cheque.update",
  "accounting.cost_sheet.close",
  "accounting.cost_sheet.confirm",
  "accounting.cost_sheet.create",
  "accounting.cost_sheet.delete",
  "accounting.cost_sheet.export",
  "accounting.cost_sheet.import",
  "accounting.cost_sheet.read",
  "accounting.cost_sheet.update",
  "accounting.credit_control.override",
  "accounting.dunning.manage",
  "accounting.dunning.read",
  "accounting.dunning.send",
  "accounting.fx_revaluation.read",
  "accounting.fx_revaluation.reverse",
  "accounting.fx_revaluation.run",
  "accounting.journal.post_control",
  "accounting.journal_entry.create",
  "accounting.journal_entry.delete",
  "accounting.journal_entry.post",
  "accounting.journal_entry.read",
  "accounting.journal_entry.reverse",
  "accounting.journal_entry.update",
  "accounting.opening_balance.manage",
  "accounting.period.lock",
  "accounting.period.override",
  "accounting.recurring.create",
  "accounting.recurring.delete",
  "accounting.recurring.generate",
  "accounting.recurring.read",
  "accounting.recurring.update",
  "accounting.voucher.cancel",
  "accounting.voucher.create",
  "accounting.voucher.delete",
  "accounting.voucher.post",
  "accounting.voucher.read",
  "accounting.voucher.update",
  "accounting.write_off.create",
  "accounting.write_off.reverse",
  "accounting.year_end.manage",
  "ai.assistant.use",
  "communication.call.create",
  "communication.call.end",
  "communication.call.join",
  "communication.call.read",
  "communication.conversation.create",
  "communication.conversation.delete",
  "communication.conversation.read",
  "communication.conversation.update",
  "communication.message.create",
  "communication.message.delete",
  "communication.message.read",
  "communication.message.update",
  "communication.presence.read",
  "crm.activity.create",
  "crm.activity.delete",
  "crm.activity.read",
  "crm.activity.update",
  "crm.campaign.create",
  "crm.campaign.delete",
  "crm.campaign.read",
  "crm.campaign.update",
  "crm.contact.create",
  "crm.contact.delete",
  "crm.contact.export",
  "crm.contact.import",
  "crm.contact.read",
  "crm.contact.update",
  "crm.customer.create",
  "crm.customer.delete",
  "crm.customer.export",
  "crm.customer.history",
  "crm.customer.import",
  "crm.customer.read",
  "crm.customer.update",
  "crm.lead.assign",
  "crm.lead.convert",
  "crm.lead.create",
  "crm.lead.delete",
  "crm.lead.export",
  "crm.lead.import",
  "crm.lead.read",
  "crm.lead.update",
  "crm.lead_source.create",
  "crm.lead_source.delete",
  "crm.lead_source.read",
  "crm.lead_source.update",
  "crm.lost_reason.create",
  "crm.lost_reason.delete",
  "crm.lost_reason.read",
  "crm.lost_reason.update",
  "crm.note.create",
  "crm.note.delete",
  "crm.note.read",
  "crm.note.update",
  "crm.opportunity.create",
  "crm.opportunity.delete",
  "crm.opportunity.export",
  "crm.opportunity.import",
  "crm.opportunity.read",
  "crm.opportunity.update",
  "crm.pipeline.create",
  "crm.pipeline.delete",
  "crm.pipeline.read",
  "crm.pipeline.update",
  "identity.attachment.create",
  "identity.attachment.delete",
  "identity.attachment.read",
  "identity.attachment.update",
  "identity.audit_log.read",
  "identity.branch.create",
  "identity.branch.delete",
  "identity.branch.read",
  "identity.branch.update",
  "identity.department.create",
  "identity.department.delete",
  "identity.department.read",
  "identity.department.update",
  "identity.employee.create",
  "identity.employee.delete",
  "identity.employee.read",
  "identity.employee.update",
  "identity.organization.read",
  "identity.organization.update",
  "identity.outbox_event.read",
  "identity.outbox_event.retry",
  "identity.permission.read",
  "identity.role.create",
  "identity.role.delete",
  "identity.role.read",
  "identity.role.update",
  "identity.user.create",
  "identity.user.delete",
  "identity.user.read",
  "identity.user.update",
  "inventory.category.create",
  "inventory.category.delete",
  "inventory.category.export",
  "inventory.category.import",
  "inventory.category.read",
  "inventory.category.update",
  "inventory.cost.read",
  "inventory.grn_charge_adjustment.create",
  "inventory.grn_charge_adjustment.delete",
  "inventory.grn_charge_adjustment.post",
  "inventory.grn_charge_adjustment.read",
  "inventory.grn_charge_adjustment.update",
  "inventory.price_list.create",
  "inventory.price_list.delete",
  "inventory.price_list.read",
  "inventory.price_list.update",
  "inventory.product.create",
  "inventory.product.delete",
  "inventory.product.export",
  "inventory.product.history",
  "inventory.product.import",
  "inventory.product.read",
  "inventory.product.update",
  "inventory.stock.read",
  "inventory.stock.update",
  "inventory.stock_adjustment.create",
  "inventory.stock_adjustment.delete",
  "inventory.stock_adjustment.post",
  "inventory.stock_adjustment.read",
  "inventory.stock_adjustment.update",
  "inventory.stock_transfer.create",
  "inventory.stock_transfer.delete",
  "inventory.stock_transfer.post",
  "inventory.stock_transfer.read",
  "inventory.stock_transfer.update",
  "inventory.unit.create",
  "inventory.unit.delete",
  "inventory.unit.export",
  "inventory.unit.import",
  "inventory.unit.read",
  "inventory.unit.update",
  "inventory.warehouse.create",
  "inventory.warehouse.delete",
  "inventory.warehouse.read",
  "inventory.warehouse.update",
  "logistics.package.create",
  "logistics.package.delete",
  "logistics.package.export",
  "logistics.package.import",
  "logistics.package.read",
  "logistics.package.update",
  "logistics.shipment.close",
  "logistics.shipment.create",
  "logistics.shipment.delete",
  "logistics.shipment.dispatch",
  "logistics.shipment.export",
  "logistics.shipment.import",
  "logistics.shipment.read",
  "logistics.shipment.update",
  "masters.cost_center.create",
  "masters.cost_center.delete",
  "masters.cost_center.read",
  "masters.cost_center.update",
  "masters.currency.create",
  "masters.currency.delete",
  "masters.currency.read",
  "masters.currency.update",
  "masters.document_sequence.create",
  "masters.document_sequence.delete",
  "masters.document_sequence.read",
  "masters.document_sequence.update",
  "masters.exchange_rate.create",
  "masters.exchange_rate.delete",
  "masters.exchange_rate.read",
  "masters.exchange_rate.update",
  "masters.payment_term.create",
  "masters.payment_term.delete",
  "masters.payment_term.read",
  "masters.payment_term.update",
  "masters.tax.create",
  "masters.tax.delete",
  "masters.tax.read",
  "masters.tax.update",
  "masters.terms_template.create",
  "masters.terms_template.delete",
  "masters.terms_template.read",
  "masters.terms_template.update",
  "purchase.debit_note.cancel",
  "purchase.debit_note.create",
  "purchase.debit_note.delete",
  "purchase.debit_note.export",
  "purchase.debit_note.import",
  "purchase.debit_note.post",
  "purchase.debit_note.read",
  "purchase.debit_note.update",
  "purchase.goods_receipt.create",
  "purchase.goods_receipt.delete",
  "purchase.goods_receipt.export",
  "purchase.goods_receipt.import",
  "purchase.goods_receipt.post",
  "purchase.goods_receipt.read",
  "purchase.goods_receipt.update",
  "purchase.purchase_invoice.cancel",
  "purchase.purchase_invoice.create",
  "purchase.purchase_invoice.delete",
  "purchase.purchase_invoice.export",
  "purchase.purchase_invoice.import",
  "purchase.purchase_invoice.post",
  "purchase.purchase_invoice.read",
  "purchase.purchase_invoice.update",
  "purchase.purchase_order.approve",
  "purchase.purchase_order.close",
  "purchase.purchase_order.create",
  "purchase.purchase_order.delete",
  "purchase.purchase_order.export",
  "purchase.purchase_order.import",
  "purchase.purchase_order.issue",
  "purchase.purchase_order.read",
  "purchase.purchase_order.update",
  "purchase.purchase_return.cancel",
  "purchase.purchase_return.create",
  "purchase.purchase_return.delete",
  "purchase.purchase_return.export",
  "purchase.purchase_return.import",
  "purchase.purchase_return.post",
  "purchase.purchase_return.read",
  "purchase.purchase_return.update",
  "purchase.quality_inspection.approve",
  "purchase.quality_inspection.create",
  "purchase.quality_inspection.read",
  "purchase.quality_inspection.update",
  "purchase.supplier.create",
  "purchase.supplier.delete",
  "purchase.supplier.export",
  "purchase.supplier.history",
  "purchase.supplier.import",
  "purchase.supplier.read",
  "purchase.supplier.update",
  "purchase.supplier_payment.cancel",
  "purchase.supplier_payment.create",
  "purchase.supplier_payment.delete",
  "purchase.supplier_payment.export",
  "purchase.supplier_payment.import",
  "purchase.supplier_payment.post",
  "purchase.supplier_payment.read",
  "purchase.supplier_payment.update",
  "purchase.supplier_product.create",
  "purchase.supplier_product.delete",
  "purchase.supplier_product.export",
  "purchase.supplier_product.import",
  "purchase.supplier_product.link",
  "purchase.supplier_product.read",
  "purchase.supplier_product.update",
  "reports.report.ar_ap",
  "reports.report.crm",
  "reports.report.day_book",
  "reports.report.export",
  "reports.report.financial",
  "reports.report.inventory",
  "reports.report.ledger",
  "reports.report.tax",
  "sales.credit_note.cancel",
  "sales.credit_note.create",
  "sales.credit_note.delete",
  "sales.credit_note.export",
  "sales.credit_note.import",
  "sales.credit_note.post",
  "sales.credit_note.read",
  "sales.credit_note.update",
  "sales.customer_payment.cancel",
  "sales.customer_payment.create",
  "sales.customer_payment.delete",
  "sales.customer_payment.export",
  "sales.customer_payment.import",
  "sales.customer_payment.post",
  "sales.customer_payment.read",
  "sales.customer_payment.update",
  "sales.delivery_note.create",
  "sales.delivery_note.delete",
  "sales.delivery_note.export",
  "sales.delivery_note.import",
  "sales.delivery_note.post",
  "sales.delivery_note.read",
  "sales.delivery_note.update",
  "sales.proforma_invoice.confirm",
  "sales.proforma_invoice.create",
  "sales.proforma_invoice.delete",
  "sales.proforma_invoice.export",
  "sales.proforma_invoice.import",
  "sales.proforma_invoice.read",
  "sales.proforma_invoice.send",
  "sales.proforma_invoice.update",
  "sales.quotation.approve",
  "sales.quotation.create",
  "sales.quotation.delete",
  "sales.quotation.export",
  "sales.quotation.import",
  "sales.quotation.read",
  "sales.quotation.revise",
  "sales.quotation.send",
  "sales.quotation.update",
  "sales.sales_invoice.cancel",
  "sales.sales_invoice.create",
  "sales.sales_invoice.delete",
  "sales.sales_invoice.export",
  "sales.sales_invoice.import",
  "sales.sales_invoice.post",
  "sales.sales_invoice.read",
  "sales.sales_invoice.update",
  "sales.sales_order.acknowledge",
  "sales.sales_order.approve",
  "sales.sales_order.close",
  "sales.sales_order.confirm",
  "sales.sales_order.create",
  "sales.sales_order.delete",
  "sales.sales_order.export",
  "sales.sales_order.import",
  "sales.sales_order.read",
  "sales.sales_order.update",
  "sales.sales_return.create",
  "sales.sales_return.delete",
  "sales.sales_return.export",
  "sales.sales_return.import",
  "sales.sales_return.post",
  "sales.sales_return.read",
  "sales.sales_return.update",
  "tasks.checklist.create",
  "tasks.checklist.delete",
  "tasks.checklist.read",
  "tasks.checklist.update",
  "tasks.comment.create",
  "tasks.comment.delete",
  "tasks.comment.read",
  "tasks.comment.update",
  "tasks.label.create",
  "tasks.label.delete",
  "tasks.label.read",
  "tasks.label.update",
  "tasks.task.assign",
  "tasks.task.create",
  "tasks.task.delete",
  "tasks.task.move",
  "tasks.task.read",
  "tasks.task.update",
  "tasks.watcher.create",
  "tasks.watcher.delete",
  "tasks.watcher.read",
] as const;

export type CatalogPermission = (typeof catalogPermissions)[number];

export const catalogPermissionSet = new Set<string>(catalogPermissions);

export function isCatalogPermission(value: string): value is CatalogPermission {
  return catalogPermissionSet.has(value);
}

export const permissionsByModule = {
  accounting: {
    account: {
      create: "accounting.account.create",
      delete: "accounting.account.delete",
      read: "accounting.account.read",
      update: "accounting.account.update",
    },
    bank_account: {
      create: "accounting.bank_account.create",
      delete: "accounting.bank_account.delete",
      read: "accounting.bank_account.read",
      update: "accounting.bank_account.update",
    },
    bank_reconciliation: {
      create: "accounting.bank_reconciliation.create",
      delete: "accounting.bank_reconciliation.delete",
      export: "accounting.bank_reconciliation.export",
      import: "accounting.bank_reconciliation.import",
      read: "accounting.bank_reconciliation.read",
      reconcile: "accounting.bank_reconciliation.reconcile",
      update: "accounting.bank_reconciliation.update",
    },
    budget: {
      activate: "accounting.budget.activate",
      close: "accounting.budget.close",
      create: "accounting.budget.create",
      delete: "accounting.budget.delete",
      read: "accounting.budget.read",
      update: "accounting.budget.update",
    },
    charge_type: {
      create: "accounting.charge_type.create",
      delete: "accounting.charge_type.delete",
      read: "accounting.charge_type.read",
      update: "accounting.charge_type.update",
    },
    cheque: {
      bounce: "accounting.cheque.bounce",
      cancel: "accounting.cheque.cancel",
      clear: "accounting.cheque.clear",
      create: "accounting.cheque.create",
      delete: "accounting.cheque.delete",
      deposit: "accounting.cheque.deposit",
      issue: "accounting.cheque.issue",
      read: "accounting.cheque.read",
      update: "accounting.cheque.update",
    },
    cost_sheet: {
      close: "accounting.cost_sheet.close",
      confirm: "accounting.cost_sheet.confirm",
      create: "accounting.cost_sheet.create",
      delete: "accounting.cost_sheet.delete",
      export: "accounting.cost_sheet.export",
      import: "accounting.cost_sheet.import",
      read: "accounting.cost_sheet.read",
      update: "accounting.cost_sheet.update",
    },
    credit_control: {
      override: "accounting.credit_control.override",
    },
    dunning: {
      manage: "accounting.dunning.manage",
      read: "accounting.dunning.read",
      send: "accounting.dunning.send",
    },
    fx_revaluation: {
      read: "accounting.fx_revaluation.read",
      reverse: "accounting.fx_revaluation.reverse",
      run: "accounting.fx_revaluation.run",
    },
    journal: {
      post_control: "accounting.journal.post_control",
    },
    journal_entry: {
      create: "accounting.journal_entry.create",
      delete: "accounting.journal_entry.delete",
      post: "accounting.journal_entry.post",
      read: "accounting.journal_entry.read",
      reverse: "accounting.journal_entry.reverse",
      update: "accounting.journal_entry.update",
    },
    opening_balance: {
      manage: "accounting.opening_balance.manage",
    },
    period: {
      lock: "accounting.period.lock",
      override: "accounting.period.override",
    },
    recurring: {
      create: "accounting.recurring.create",
      delete: "accounting.recurring.delete",
      generate: "accounting.recurring.generate",
      read: "accounting.recurring.read",
      update: "accounting.recurring.update",
    },
    voucher: {
      cancel: "accounting.voucher.cancel",
      create: "accounting.voucher.create",
      delete: "accounting.voucher.delete",
      post: "accounting.voucher.post",
      read: "accounting.voucher.read",
      update: "accounting.voucher.update",
    },
    write_off: {
      create: "accounting.write_off.create",
      reverse: "accounting.write_off.reverse",
    },
    year_end: {
      manage: "accounting.year_end.manage",
    },
  },
  ai: {
    assistant: {
      use: "ai.assistant.use",
    },
  },
  communication: {
    call: {
      create: "communication.call.create",
      end: "communication.call.end",
      join: "communication.call.join",
      read: "communication.call.read",
    },
    conversation: {
      create: "communication.conversation.create",
      delete: "communication.conversation.delete",
      read: "communication.conversation.read",
      update: "communication.conversation.update",
    },
    message: {
      create: "communication.message.create",
      delete: "communication.message.delete",
      read: "communication.message.read",
      update: "communication.message.update",
    },
    presence: {
      read: "communication.presence.read",
    },
  },
  crm: {
    activity: {
      create: "crm.activity.create",
      delete: "crm.activity.delete",
      read: "crm.activity.read",
      update: "crm.activity.update",
    },
    campaign: {
      create: "crm.campaign.create",
      delete: "crm.campaign.delete",
      read: "crm.campaign.read",
      update: "crm.campaign.update",
    },
    contact: {
      create: "crm.contact.create",
      delete: "crm.contact.delete",
      export: "crm.contact.export",
      import: "crm.contact.import",
      read: "crm.contact.read",
      update: "crm.contact.update",
    },
    customer: {
      create: "crm.customer.create",
      delete: "crm.customer.delete",
      export: "crm.customer.export",
      history: "crm.customer.history",
      import: "crm.customer.import",
      read: "crm.customer.read",
      update: "crm.customer.update",
    },
    lead: {
      assign: "crm.lead.assign",
      convert: "crm.lead.convert",
      create: "crm.lead.create",
      delete: "crm.lead.delete",
      export: "crm.lead.export",
      import: "crm.lead.import",
      read: "crm.lead.read",
      update: "crm.lead.update",
    },
    lead_source: {
      create: "crm.lead_source.create",
      delete: "crm.lead_source.delete",
      read: "crm.lead_source.read",
      update: "crm.lead_source.update",
    },
    lost_reason: {
      create: "crm.lost_reason.create",
      delete: "crm.lost_reason.delete",
      read: "crm.lost_reason.read",
      update: "crm.lost_reason.update",
    },
    note: {
      create: "crm.note.create",
      delete: "crm.note.delete",
      read: "crm.note.read",
      update: "crm.note.update",
    },
    opportunity: {
      create: "crm.opportunity.create",
      delete: "crm.opportunity.delete",
      export: "crm.opportunity.export",
      import: "crm.opportunity.import",
      read: "crm.opportunity.read",
      update: "crm.opportunity.update",
    },
    pipeline: {
      create: "crm.pipeline.create",
      delete: "crm.pipeline.delete",
      read: "crm.pipeline.read",
      update: "crm.pipeline.update",
    },
  },
  identity: {
    attachment: {
      create: "identity.attachment.create",
      delete: "identity.attachment.delete",
      read: "identity.attachment.read",
      update: "identity.attachment.update",
    },
    audit_log: {
      read: "identity.audit_log.read",
    },
    branch: {
      create: "identity.branch.create",
      delete: "identity.branch.delete",
      read: "identity.branch.read",
      update: "identity.branch.update",
    },
    department: {
      create: "identity.department.create",
      delete: "identity.department.delete",
      read: "identity.department.read",
      update: "identity.department.update",
    },
    employee: {
      create: "identity.employee.create",
      delete: "identity.employee.delete",
      read: "identity.employee.read",
      update: "identity.employee.update",
    },
    organization: {
      read: "identity.organization.read",
      update: "identity.organization.update",
    },
    outbox_event: {
      read: "identity.outbox_event.read",
      retry: "identity.outbox_event.retry",
    },
    permission: {
      read: "identity.permission.read",
    },
    role: {
      create: "identity.role.create",
      delete: "identity.role.delete",
      read: "identity.role.read",
      update: "identity.role.update",
    },
    user: {
      create: "identity.user.create",
      delete: "identity.user.delete",
      read: "identity.user.read",
      update: "identity.user.update",
    },
  },
  inventory: {
    category: {
      create: "inventory.category.create",
      delete: "inventory.category.delete",
      export: "inventory.category.export",
      import: "inventory.category.import",
      read: "inventory.category.read",
      update: "inventory.category.update",
    },
    cost: {
      read: "inventory.cost.read",
    },
    grn_charge_adjustment: {
      create: "inventory.grn_charge_adjustment.create",
      delete: "inventory.grn_charge_adjustment.delete",
      post: "inventory.grn_charge_adjustment.post",
      read: "inventory.grn_charge_adjustment.read",
      update: "inventory.grn_charge_adjustment.update",
    },
    price_list: {
      create: "inventory.price_list.create",
      delete: "inventory.price_list.delete",
      read: "inventory.price_list.read",
      update: "inventory.price_list.update",
    },
    product: {
      create: "inventory.product.create",
      delete: "inventory.product.delete",
      export: "inventory.product.export",
      history: "inventory.product.history",
      import: "inventory.product.import",
      read: "inventory.product.read",
      update: "inventory.product.update",
    },
    stock: {
      read: "inventory.stock.read",
      update: "inventory.stock.update",
    },
    stock_adjustment: {
      create: "inventory.stock_adjustment.create",
      delete: "inventory.stock_adjustment.delete",
      post: "inventory.stock_adjustment.post",
      read: "inventory.stock_adjustment.read",
      update: "inventory.stock_adjustment.update",
    },
    stock_transfer: {
      create: "inventory.stock_transfer.create",
      delete: "inventory.stock_transfer.delete",
      post: "inventory.stock_transfer.post",
      read: "inventory.stock_transfer.read",
      update: "inventory.stock_transfer.update",
    },
    unit: {
      create: "inventory.unit.create",
      delete: "inventory.unit.delete",
      export: "inventory.unit.export",
      import: "inventory.unit.import",
      read: "inventory.unit.read",
      update: "inventory.unit.update",
    },
    warehouse: {
      create: "inventory.warehouse.create",
      delete: "inventory.warehouse.delete",
      read: "inventory.warehouse.read",
      update: "inventory.warehouse.update",
    },
  },
  logistics: {
    package: {
      create: "logistics.package.create",
      delete: "logistics.package.delete",
      export: "logistics.package.export",
      import: "logistics.package.import",
      read: "logistics.package.read",
      update: "logistics.package.update",
    },
    shipment: {
      close: "logistics.shipment.close",
      create: "logistics.shipment.create",
      delete: "logistics.shipment.delete",
      dispatch: "logistics.shipment.dispatch",
      export: "logistics.shipment.export",
      import: "logistics.shipment.import",
      read: "logistics.shipment.read",
      update: "logistics.shipment.update",
    },
  },
  masters: {
    cost_center: {
      create: "masters.cost_center.create",
      delete: "masters.cost_center.delete",
      read: "masters.cost_center.read",
      update: "masters.cost_center.update",
    },
    currency: {
      create: "masters.currency.create",
      delete: "masters.currency.delete",
      read: "masters.currency.read",
      update: "masters.currency.update",
    },
    document_sequence: {
      create: "masters.document_sequence.create",
      delete: "masters.document_sequence.delete",
      read: "masters.document_sequence.read",
      update: "masters.document_sequence.update",
    },
    exchange_rate: {
      create: "masters.exchange_rate.create",
      delete: "masters.exchange_rate.delete",
      read: "masters.exchange_rate.read",
      update: "masters.exchange_rate.update",
    },
    payment_term: {
      create: "masters.payment_term.create",
      delete: "masters.payment_term.delete",
      read: "masters.payment_term.read",
      update: "masters.payment_term.update",
    },
    tax: {
      create: "masters.tax.create",
      delete: "masters.tax.delete",
      read: "masters.tax.read",
      update: "masters.tax.update",
    },
    terms_template: {
      create: "masters.terms_template.create",
      delete: "masters.terms_template.delete",
      read: "masters.terms_template.read",
      update: "masters.terms_template.update",
    },
  },
  purchase: {
    debit_note: {
      cancel: "purchase.debit_note.cancel",
      create: "purchase.debit_note.create",
      delete: "purchase.debit_note.delete",
      export: "purchase.debit_note.export",
      import: "purchase.debit_note.import",
      post: "purchase.debit_note.post",
      read: "purchase.debit_note.read",
      update: "purchase.debit_note.update",
    },
    goods_receipt: {
      create: "purchase.goods_receipt.create",
      delete: "purchase.goods_receipt.delete",
      export: "purchase.goods_receipt.export",
      import: "purchase.goods_receipt.import",
      post: "purchase.goods_receipt.post",
      read: "purchase.goods_receipt.read",
      update: "purchase.goods_receipt.update",
    },
    purchase_invoice: {
      cancel: "purchase.purchase_invoice.cancel",
      create: "purchase.purchase_invoice.create",
      delete: "purchase.purchase_invoice.delete",
      export: "purchase.purchase_invoice.export",
      import: "purchase.purchase_invoice.import",
      post: "purchase.purchase_invoice.post",
      read: "purchase.purchase_invoice.read",
      update: "purchase.purchase_invoice.update",
    },
    purchase_order: {
      approve: "purchase.purchase_order.approve",
      close: "purchase.purchase_order.close",
      create: "purchase.purchase_order.create",
      delete: "purchase.purchase_order.delete",
      export: "purchase.purchase_order.export",
      import: "purchase.purchase_order.import",
      issue: "purchase.purchase_order.issue",
      read: "purchase.purchase_order.read",
      update: "purchase.purchase_order.update",
    },
    purchase_return: {
      cancel: "purchase.purchase_return.cancel",
      create: "purchase.purchase_return.create",
      delete: "purchase.purchase_return.delete",
      export: "purchase.purchase_return.export",
      import: "purchase.purchase_return.import",
      post: "purchase.purchase_return.post",
      read: "purchase.purchase_return.read",
      update: "purchase.purchase_return.update",
    },
    quality_inspection: {
      approve: "purchase.quality_inspection.approve",
      create: "purchase.quality_inspection.create",
      read: "purchase.quality_inspection.read",
      update: "purchase.quality_inspection.update",
    },
    supplier: {
      create: "purchase.supplier.create",
      delete: "purchase.supplier.delete",
      export: "purchase.supplier.export",
      history: "purchase.supplier.history",
      import: "purchase.supplier.import",
      read: "purchase.supplier.read",
      update: "purchase.supplier.update",
    },
    supplier_payment: {
      cancel: "purchase.supplier_payment.cancel",
      create: "purchase.supplier_payment.create",
      delete: "purchase.supplier_payment.delete",
      export: "purchase.supplier_payment.export",
      import: "purchase.supplier_payment.import",
      post: "purchase.supplier_payment.post",
      read: "purchase.supplier_payment.read",
      update: "purchase.supplier_payment.update",
    },
    supplier_product: {
      create: "purchase.supplier_product.create",
      delete: "purchase.supplier_product.delete",
      export: "purchase.supplier_product.export",
      import: "purchase.supplier_product.import",
      link: "purchase.supplier_product.link",
      read: "purchase.supplier_product.read",
      update: "purchase.supplier_product.update",
    },
  },
  reports: {
    report: {
      ar_ap: "reports.report.ar_ap",
      crm: "reports.report.crm",
      day_book: "reports.report.day_book",
      export: "reports.report.export",
      financial: "reports.report.financial",
      inventory: "reports.report.inventory",
      ledger: "reports.report.ledger",
      tax: "reports.report.tax",
    },
  },
  sales: {
    credit_note: {
      cancel: "sales.credit_note.cancel",
      create: "sales.credit_note.create",
      delete: "sales.credit_note.delete",
      export: "sales.credit_note.export",
      import: "sales.credit_note.import",
      post: "sales.credit_note.post",
      read: "sales.credit_note.read",
      update: "sales.credit_note.update",
    },
    customer_payment: {
      cancel: "sales.customer_payment.cancel",
      create: "sales.customer_payment.create",
      delete: "sales.customer_payment.delete",
      export: "sales.customer_payment.export",
      import: "sales.customer_payment.import",
      post: "sales.customer_payment.post",
      read: "sales.customer_payment.read",
      update: "sales.customer_payment.update",
    },
    delivery_note: {
      create: "sales.delivery_note.create",
      delete: "sales.delivery_note.delete",
      export: "sales.delivery_note.export",
      import: "sales.delivery_note.import",
      post: "sales.delivery_note.post",
      read: "sales.delivery_note.read",
      update: "sales.delivery_note.update",
    },
    proforma_invoice: {
      confirm: "sales.proforma_invoice.confirm",
      create: "sales.proforma_invoice.create",
      delete: "sales.proforma_invoice.delete",
      export: "sales.proforma_invoice.export",
      import: "sales.proforma_invoice.import",
      read: "sales.proforma_invoice.read",
      send: "sales.proforma_invoice.send",
      update: "sales.proforma_invoice.update",
    },
    quotation: {
      approve: "sales.quotation.approve",
      create: "sales.quotation.create",
      delete: "sales.quotation.delete",
      export: "sales.quotation.export",
      import: "sales.quotation.import",
      read: "sales.quotation.read",
      revise: "sales.quotation.revise",
      send: "sales.quotation.send",
      update: "sales.quotation.update",
    },
    sales_invoice: {
      cancel: "sales.sales_invoice.cancel",
      create: "sales.sales_invoice.create",
      delete: "sales.sales_invoice.delete",
      export: "sales.sales_invoice.export",
      import: "sales.sales_invoice.import",
      post: "sales.sales_invoice.post",
      read: "sales.sales_invoice.read",
      update: "sales.sales_invoice.update",
    },
    sales_order: {
      acknowledge: "sales.sales_order.acknowledge",
      approve: "sales.sales_order.approve",
      close: "sales.sales_order.close",
      confirm: "sales.sales_order.confirm",
      create: "sales.sales_order.create",
      delete: "sales.sales_order.delete",
      export: "sales.sales_order.export",
      import: "sales.sales_order.import",
      read: "sales.sales_order.read",
      update: "sales.sales_order.update",
    },
    sales_return: {
      create: "sales.sales_return.create",
      delete: "sales.sales_return.delete",
      export: "sales.sales_return.export",
      import: "sales.sales_return.import",
      post: "sales.sales_return.post",
      read: "sales.sales_return.read",
      update: "sales.sales_return.update",
    },
  },
  tasks: {
    checklist: {
      create: "tasks.checklist.create",
      delete: "tasks.checklist.delete",
      read: "tasks.checklist.read",
      update: "tasks.checklist.update",
    },
    comment: {
      create: "tasks.comment.create",
      delete: "tasks.comment.delete",
      read: "tasks.comment.read",
      update: "tasks.comment.update",
    },
    label: {
      create: "tasks.label.create",
      delete: "tasks.label.delete",
      read: "tasks.label.read",
      update: "tasks.label.update",
    },
    task: {
      assign: "tasks.task.assign",
      create: "tasks.task.create",
      delete: "tasks.task.delete",
      move: "tasks.task.move",
      read: "tasks.task.read",
      update: "tasks.task.update",
    },
    watcher: {
      create: "tasks.watcher.create",
      delete: "tasks.watcher.delete",
      read: "tasks.watcher.read",
    },
  },
} as const;
